name: condorapp
description: "A new Flutter project."
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ^3.5.3

dependencies:
  flutter:
    sdk: flutter
  
  # Existing UI components for iOS
  cupertino_icons: ^1.0.8
  
  # HTTP client and API handling
  dio: ^5.7.0
  
  # State management
  provider: ^6.1.2
  
  # Data persistence
  shared_preferences: ^2.3.2
  flutter_secure_storage: ^9.2.2
  
  # Date formatting and localization
  intl: ^0.19.0
  
  # WebSocket client
  stomp_dart_client: ^2.1.0
  
  # SVG handling for assets
  flutter_svg: ^1.0.3

  flutter_animate: ^4.4.0
  lucide_icons: ^0.257.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/logo.png
    - assets/google.svg
    - assets/apple.svg
    - assets/facebook.svg